### ISSUE TITLE
NO VERSION FILE TO GET IN 'migrate.sh'

### ISSUE THREAD

**Issue by Zombie1226** [TencentBlueKing/bk-hcm#307]
The script 'migrate.sh' cannot get the VERSION info from '../VERSION'

/data/bk-hcm/hcm/scripts/install# sh migrate.sh -i
head: cannot open '../VERSION' for reading: No such file or directory
[ERROR] Fail to get target version! Please use -t to specify version, or -a to specify version file.
migrate.sh: 116: exit: Illegal number: -1

**Comment by chenjr15** [comment]
Please add `-t vx.y.z` to specify the target version. 

Currently, the latest version for the `master` or `v1.0` branch is `v1.1.27`.
