### ISSUE TITLE
部署出来前端界面不停的跳转

### ISSUE THREAD

**Issue by hanlearned** [TencentBlueKing/bk-hcm#532]
一直报错 bk_token 不存在。

**Comment by chenjr15** [comment]
web-server依赖`bk_token`传递登录信息，请确认cookie 中是否有`bk_token`。

如果没有的话请检查配置的域名是否和`bkLoginUrl`配置在同一个域下。

**Comment by wealth-engine** [comment]
是哪个配置的域名需要和 bkLoginUrl  一致？

**Comment by hanlearned** [comment]
请问是哪个 配置的域名 需要和 bkLoginUrl 配置在同一个域下？

**Comment by hanlearned** [comment]
![image](https://github.com/TencentBlueKing/bk-hcm/assets/54702352/9508111b-6060-4a0c-8c9f-5b2234cb1fb8)
请问是这两个配置保持一致吗？

**Comment by chenjr15** [comment]
是访问web server 的域名，不是`bkDomain`配置。你浏览器访问web server的url地址需要和`bkLoginUrl`在同一个域名下。

当你打开登录页面的时候，webserver检测到没有bk_token cookie，于是跳转到bkLoginUrl 配置的url完成蓝鲸统一登录，蓝鲸统一登录会给你设置`bk_token` cookie，然后跳回到webserver，检测到bk_token 即可完成登录。

看你的情况并没有配置域名，而是用ip，统一登录和webserver是同一个ip吗？

如果不是同一个ip那就肯定不符合同一个域下的条件，cookie无法传递到webserver，会重复跳转登录。

建议配置hosts达到统一域名的效果。

**Comment by hanlearned** [comment]
![image](https://github.com/TencentBlueKing/bk-hcm/assets/54702352/c11c1663-41a3-46f1-a4fa-45d3b501111c)
根据你说的server 域名和 统一登陆域名，我这里是同一个 IP，但是还是会出现跳转问题。

**Comment by chenjr15** [comment]
您好，报 `bk_token`不存在说明没有读到cookie，后端无法完成用户鉴权。
需要确认是否有正确的`bk_token` cookie，以及统一登录是否配置正确。
可以尝试通过浏览器 f12-> application->cookies 查看是否存在`bk_token` cookie。
<img width="666" alt="image" src="https://github.com/TencentBlueKing/bk-hcm/assets/24223746/f368a381-5052-434a-8e58-6c6c91cd0b25">
<img width="909" alt="image" src="https://github.com/TencentBlueKing/bk-hcm/assets/24223746/965fe9f2-e8e5-429d-9243-2455be39a33a">

**Comment by hanlearned** [comment]
您好，我看了浏览器，确实找不到这个 Cookie。但是不知道如何解决这个问题。因为我没有域名， 是配置 bkLoginUrl 是用的IP地址。访问server的ip和 bkLoginUrl是 统一 IP，还是出现这个问题，现在不知道如何解决了。

**Comment by chenjr15** [comment]
您好，统一登录相关的问题可以到蓝鲸论坛提问 https://bk.tencent.com/s-mart/community/question。
