### ISSUE TITLE
我们已经部署了蓝鲸社区版 7.1（包含了 cmdb）， 部署开源版的 bk-hcm 支持和蓝鲸体系的 cmdb 集成吗？

### ISSUE THREAD

**Issue by dehengxupix** [TencentBlueKing/bk-hcm#721]
我们已经部署了蓝鲸社区版 7.1（包含了 cmdb）， 部署开源版的 bk-hcm 支持和蓝鲸体系的 cmdb 集成吗？

**Comment by chenjr15** [comment]
您好，可以的，二进制部署可以参考 docs/overview/installation.md 中的文档，配置好etc目录下的配置文件中esb 和api 网关地址即可。
